# Generated by Django 5.1.3 on 2024-11-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=100)),
                ('airline_id', models.CharField(max_length=50)),
                ('source_airport', models.CharField(max_length=100)),
                ('source_airport_id', models.CharField(max_length=50)),
                ('destination_airport', models.CharField(max_length=100)),
                ('destination_airport_id', models.CharField(max_length=50)),
                ('codeshare', models.CharField(blank=True, max_length=10, null=True)),
                ('stops', models.IntegerField()),
                ('equipment', models.CharField(blank=True, max_length=100, null=True)),
                ('source_coords', models.CharField(max_length=100)),
                ('destination_coords', models.CharField(max_length=100)),
            ],
        ),
    ]
